
# Runs protoc when merging changes to main branch
name: Protoc on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:alpine3.17

    steps:

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache protobuf git make protoc protobuf-dev

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "export PATH=$PATH:$GOPATH/bin"

      - name: generate protogen
        run: |
          make build

      - name: Commit and push changes
        run: |
          git config --global --add safe.directory /__w/grpc-protobuf/grpc-protobuf
          git config user.name "github workflow"
          git config user.email "action@github.com"
          git add -A
          git commit -m " [skip actions] Generated Protogen files"
          git push
